alias slogger="~/projects/Slogger/slogger"
alias cdsales="cd ~/DropBox/Public/statusboard_data/Salesboard/"
alias salesup="ruby ~/Dropbox/Public/statusboard_data/Salesboard/salesboard.rb"
alias gitweb="git instaweb -d webrick --start"
alias sshwiki="ssh serveradmin@wiki.trilby.co.uk -p 3322"
alias sshxcode="ssh serveradmin@wiki.trilby.co.uk -p 3323"
alias ll="ls -lahL"
alias fuck='sudo $(history -p \!\!)'
alias unhide='defaults write com.apple.finder AppleShowAllFiles YES'
alias rehide='defaults write com.apple.finder AppleShowAllFiles NO'
